name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Use Node.js 22.2
        uses: actions/setup-node@v4
        with:
          node-version: 22.2

      - name: Install Dependencies
        run: cd 03 && npm install

      - name: Run tests
        run: |
          cd 03 && npm run test
